//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложушечка.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Specification { get; set; }
        public string Otdel { get; set; }
        public System.DateTime Birthday { get; set; }
    }
}
